"""Create and run built-in figure recipes."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import os
import subprocess
import sys

from repromath.figures.registry import FIGURE_RECIPES


class FigureScaffoldError(Exception):
    """Raised when a figure recipe cannot be scaffolded safely."""


@dataclass(frozen=True)
class FigureScaffoldResult:
    recipe_name: str
    script_path: str
    figure_path: str
    note_path: str
    returncode: int
    stdout: str
    stderr: str


def create_figure_recipe(recipe_name: str, base_dir: Path | None = None) -> FigureScaffoldResult:
    if recipe_name not in FIGURE_RECIPES:
        valid = ", ".join(sorted(FIGURE_RECIPES))
        raise FigureScaffoldError(
            f"Unknown figure recipe '{recipe_name}'. Expected one of: {valid}."
        )

    root = base_dir or Path.cwd()
    figures_dir = root / "figures"
    script_path = (figures_dir / f"{recipe_name}.py").resolve()
    figure_path = script_path.with_suffix(".pdf")
    note_path = script_path.with_suffix(".md")

    existing = [path for path in (script_path, figure_path, note_path) if path.exists()]
    if existing:
        joined = ", ".join(str(path) for path in existing)
        raise FigureScaffoldError(f"Refusing to overwrite existing figure files: {joined}")

    recipe = FIGURE_RECIPES[recipe_name]
    figures_dir.mkdir(parents=True, exist_ok=True)
    script_path.write_text(recipe.script_factory(), encoding="utf-8")
    note_path.write_text(_note(recipe_name, recipe.description), encoding="utf-8")

    env = {
        **os.environ,
        "MPLCONFIGDIR": str(figures_dir / ".matplotlib-cache"),
    }
    completed = subprocess.run(
        [sys.executable, str(script_path)],
        check=False,
        capture_output=True,
        env=env,
        text=True,
    )
    if completed.returncode != 0:
        raise FigureScaffoldError(
            f"Figure recipe '{recipe_name}' failed with exit code {completed.returncode}: "
            f"{completed.stderr.strip() or completed.stdout.strip()}"
        )
    if not figure_path.is_file():
        raise FigureScaffoldError(
            f"Figure recipe '{recipe_name}' ran but did not create {figure_path}."
        )

    return FigureScaffoldResult(
        recipe_name=recipe_name,
        script_path=str(script_path),
        figure_path=str(figure_path),
        note_path=str(note_path),
        returncode=completed.returncode,
        stdout=completed.stdout,
        stderr=completed.stderr,
    )


def _note(recipe_name: str, description: str) -> str:
    return f"""# {recipe_name}

{description}

Generated by `repromath scaffold figure {recipe_name}`.
The Python script next to this note regenerates the figure deterministically.
"""

