"""Project initialization helpers for ReproMath."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


class ProjectInitError(Exception):
    """Raised when a ReproMath project cannot be initialized safely."""


@dataclass(frozen=True)
class ProjectTemplate:
    project_type: str
    description: str
    extra_directories: tuple[str, ...]
    extra_files: tuple[tuple[str, str], ...] = ()


PROJECT_TEMPLATES: dict[str, ProjectTemplate] = {
    "dissertation": ProjectTemplate(
        project_type="dissertation",
        description=(
            "A dissertation-oriented ReproMath project for notebooks, figures, "
            "LaTeX writing, and QA reports."
        ),
        extra_directories=("thesis/sections", "thesis/figures"),
        extra_files=(
            (
                "thesis/main.tex",
                r"""\documentclass{article}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{graphicx}

\title{ReproMath Dissertation Project}
\author{}
\date{}

\begin{document}
\maketitle

\section{Project Overview}

This is a minimal dissertation scaffold generated by ReproMath.

\end{document}
""",
            ),
        ),
    ),
    "paper-study": ProjectTemplate(
        project_type="paper-study",
        description=(
            "A paper-study ReproMath project for theorem notes, source files, "
            "structured notebooks, and QA reports."
        ),
        extra_directories=("notes",),
    ),
    "numerical-experiment": ProjectTemplate(
        project_type="numerical-experiment",
        description=(
            "A numerical-experiment ReproMath project for experiments, "
            "notebooks, figures, and reproducibility reports."
        ),
        extra_directories=("experiments",),
    ),
}

COMMON_DIRECTORIES = ("notebooks", "figures", "reports", "sources")


def create_project(
    project_type: str,
    project_name: str,
    base_dir: Path | None = None,
) -> Path:
    """Create a new ReproMath project and return its path."""

    if project_type not in PROJECT_TEMPLATES:
        valid_types = ", ".join(sorted(PROJECT_TEMPLATES))
        raise ProjectInitError(
            f"Unknown project type '{project_type}'. Expected one of: {valid_types}."
        )

    if not project_name.strip():
        raise ProjectInitError("Project name cannot be empty.")

    root = Path(project_name).expanduser()
    if not root.is_absolute():
        root = (base_dir or Path.cwd()) / root
    root = root.resolve()

    if root.exists():
        raise ProjectInitError(
            f"Refusing to initialize project because '{root}' already exists."
        )

    template = PROJECT_TEMPLATES[project_type]
    root.mkdir(parents=True)

    for directory in COMMON_DIRECTORIES + template.extra_directories:
        (root / directory).mkdir(parents=True, exist_ok=True)

    _write_text(root / "README.md", _project_readme(project_name=root.name, template=template))
    _write_text(root / "repromath.toml", _project_toml(project_name=root.name, template=template))

    for relative_path, contents in template.extra_files:
        _write_text(root / relative_path, contents)

    return root


def _project_readme(project_name: str, template: ProjectTemplate) -> str:
    return f"""# {project_name}

{template.description}

This project was initialized with ReproMath.

## Suggested Workflow

1. Put source papers, notes, or datasets in `sources/`.
2. Use `notebooks/` for study-first notebooks and numerical experiments.
3. Save reusable figures in `figures/`.
4. Keep generated QA reports in `reports/`.
"""


def _project_toml(project_name: str, template: ProjectTemplate) -> str:
    project_lines = [
        "[project]",
        f'name = "{project_name}"',
        f'type = "{template.project_type}"',
    ]
    if template.project_type == "dissertation":
        project_lines.append('main_tex = "thesis/main.tex"')

    return (
        "\n".join(project_lines)
        + """

[paths]
notebooks = "notebooks"
figures = "figures"
reports = "reports"
sources = "sources"
"""
    )


def _write_text(path: Path, contents: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents, encoding="utf-8")

